/**
 * Product catalog — GENERATED by python/catalog_publisher.py.
 *
 * Do not edit by hand. Canonical, validated inputs live under
 * catalog/merchant-catalogs/. Run `npm run catalog:generate` to regenerate or
 * `npm run catalog:check` to detect drift.
 */

export interface ProductPricing {
  merchant_subtotal_usd: string;
  estimated_tax_buffer_usd: string;
  shipping_buffer_usd: string;
  service_fee_usd: string;
  service_markup_bps: number;
  all_inclusive: true;
  total_usd: string;
}

export interface Product {
  id: string;
  merchant?: {
    nickname: string;
    display_name: string;
    fulfillment: 'pickup' | 'shipping';
  };
  name: string;
  description: string;
  /** All-inclusive USDC price charged via x402, in dollars. */
  price_usd: string;
  /** Underlying merchant package price before buffers and service fee. */
  merchant_price_usd?: string;
  pricing?: ProductPricing;
  /** Internal fulfillment target; omitted from public API responses. */
  source_url?: string;
}

export const catalogProvenance = {
  generator: 'python/catalog_publisher.py',
  generator_version: 1,
  manifests: [
    {
      "merchant": "mcmaster",
      "sha256": "1a79640ab51f644ea12bed53c27b60abe84f2a828783e594bb44600ad7b5aed2",
      "source": "catalog/merchant-catalogs/mcmaster.json"
    }
  ],
} as const;

export const catalog: Record<string, Product> = {
  "mcmaster:92224A100": {
    "id": "mcmaster:92224A100",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 1/8 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 1/8 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A100.",
    "price_usd": "$31.74",
    "merchant_price_usd": "$13.39",
    "pricing": {
      "merchant_subtotal_usd": "13.39",
      "estimated_tax_buffer_usd": "1.34",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "2.01",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "31.74"
    },
    "source_url": "https://www.mcmaster.com/92224A100"
  },
  "mcmaster:92224A101": {
    "id": "mcmaster:92224A101",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 3/16 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 3/16 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A101.",
    "price_usd": "$29.41",
    "merchant_price_usd": "$11.52",
    "pricing": {
      "merchant_subtotal_usd": "11.52",
      "estimated_tax_buffer_usd": "1.16",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.73",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "29.41"
    },
    "source_url": "https://www.mcmaster.com/92224A101"
  },
  "mcmaster:92224A102": {
    "id": "mcmaster:92224A102",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 1/4 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 1/4 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A102.",
    "price_usd": "$27.66",
    "merchant_price_usd": "$10.12",
    "pricing": {
      "merchant_subtotal_usd": "10.12",
      "estimated_tax_buffer_usd": "1.02",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.52",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "27.66"
    },
    "source_url": "https://www.mcmaster.com/92224A102"
  },
  "mcmaster:92224A103": {
    "id": "mcmaster:92224A103",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 5/16 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 5/16 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A103.",
    "price_usd": "$28.53",
    "merchant_price_usd": "$10.81",
    "pricing": {
      "merchant_subtotal_usd": "10.81",
      "estimated_tax_buffer_usd": "1.09",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.63",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "28.53"
    },
    "source_url": "https://www.mcmaster.com/92224A103"
  },
  "mcmaster:92224A104": {
    "id": "mcmaster:92224A104",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 3/8 inch (pack of 50)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 3/8 inch length, Black-Oxide Steel, Fully Threaded Package of 50. McMaster-Carr part 92224A104.",
    "price_usd": "$25.74",
    "merchant_price_usd": "$8.59",
    "pricing": {
      "merchant_subtotal_usd": "8.59",
      "estimated_tax_buffer_usd": "0.86",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.29",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "25.74"
    },
    "source_url": "https://www.mcmaster.com/92224A104"
  },
  "mcmaster:92224A105": {
    "id": "mcmaster:92224A105",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 7/16 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 7/16 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A105.",
    "price_usd": "$28.91",
    "merchant_price_usd": "$11.12",
    "pricing": {
      "merchant_subtotal_usd": "11.12",
      "estimated_tax_buffer_usd": "1.12",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.67",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "28.91"
    },
    "source_url": "https://www.mcmaster.com/92224A105"
  },
  "mcmaster:92224A106": {
    "id": "mcmaster:92224A106",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 2-56 x 1/2 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 2-56 thread, 1/2 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A106.",
    "price_usd": "$29.05",
    "merchant_price_usd": "$11.23",
    "pricing": {
      "merchant_subtotal_usd": "11.23",
      "estimated_tax_buffer_usd": "1.13",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.69",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "29.05"
    },
    "source_url": "https://www.mcmaster.com/92224A106"
  },
  "mcmaster:92224A109": {
    "id": "mcmaster:92224A109",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 3-48 x 3/8 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 3-48 thread, 3/8 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A109.",
    "price_usd": "$31.67",
    "merchant_price_usd": "$13.33",
    "pricing": {
      "merchant_subtotal_usd": "13.33",
      "estimated_tax_buffer_usd": "1.34",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "2.00",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "31.67"
    },
    "source_url": "https://www.mcmaster.com/92224A109"
  },
  "mcmaster:92224A111": {
    "id": "mcmaster:92224A111",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 4-40 x 3/16 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 4-40 thread, 3/16 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A111.",
    "price_usd": "$22.04",
    "merchant_price_usd": "$5.49",
    "pricing": {
      "merchant_subtotal_usd": "5.49",
      "estimated_tax_buffer_usd": "0.55",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.00",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "22.04"
    },
    "source_url": "https://www.mcmaster.com/92224A111"
  },
  "mcmaster:92224A112": {
    "id": "mcmaster:92224A112",
    "merchant": {
      "nickname": "mcmaster",
      "display_name": "McMaster-Carr",
      "fulfillment": "shipping"
    },
    "name": "Steel Pan Head Phillips Screw 4-40 x 1/4 inch (pack of 100)",
    "description": "Steel Pan Head Phillips Screw, 4-40 thread, 1/4 inch length, Black-Oxide Steel, Fully Threaded Package of 100. McMaster-Carr part 92224A112.",
    "price_usd": "$21.90",
    "merchant_price_usd": "$5.36",
    "pricing": {
      "merchant_subtotal_usd": "5.36",
      "estimated_tax_buffer_usd": "0.54",
      "shipping_buffer_usd": "15.00",
      "service_fee_usd": "1.00",
      "service_markup_bps": 1500,
      "all_inclusive": true,
      "total_usd": "21.90"
    },
    "source_url": "https://www.mcmaster.com/92224A112"
  },
  'test-item': {
    id: 'test-item',
    name: 'Test Item (integration test, no fulfillment)',
    description:
      'A ten-cent item for testing the x402 purchase flow end to end. ' +
      'Fulfillment completes immediately without contacting any merchant.',
    price_usd: '$0.10',
  },
};

export function listProducts() {
  return Object.values(catalog).map(({ source_url, ...rest }) => rest);
}

export function getProduct(id: string): Product | undefined {
  return catalog[id];
}
