export const workshopHtml = String.raw`<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>BuyWith402 · Voice Workshop</title>
  <style>
    :root{color-scheme:dark;--ink:#f5f1e8;--muted:#9e9b95;--line:#34342f;--panel:#181916;--lime:#c9ff58;--orange:#ff774d;--blue:#72a9ff}
    *{box-sizing:border-box} body{margin:0;background:#10110f;color:var(--ink);font:15px/1.5 Inter,ui-sans-serif,system-ui,sans-serif;min-height:100vh}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;background:radial-gradient(circle at 18% 8%,#25351c 0,transparent 29%),radial-gradient(circle at 92% 70%,#222d3a 0,transparent 30%);opacity:.65}
    button,input,textarea{font:inherit}.shell{position:relative;max-width:1180px;margin:auto;padding:28px 24px 64px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:48px}
    .brand{font-weight:800;letter-spacing:-.03em;font-size:19px}.brand i{display:inline-block;width:11px;height:11px;background:var(--lime);border-radius:50%;margin-right:9px;box-shadow:0 0 25px #c9ff5870}
    .tag{border:1px solid var(--line);border-radius:999px;padding:7px 11px;color:var(--muted);font-size:12px}.tag b{color:var(--ink)}
    .hero{display:grid;grid-template-columns:1.15fr .85fr;gap:54px;align-items:end;margin-bottom:34px}.eyebrow{color:var(--lime);text-transform:uppercase;letter-spacing:.16em;font-size:11px;font-weight:800}
    h1{font-size:clamp(45px,6vw,78px);letter-spacing:-.065em;line-height:.94;margin:12px 0 18px;max-width:760px}.sub{max-width:650px;color:#bbb9b3;font-size:17px}
    .flow{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);border-radius:15px;overflow:hidden;background:#151613}.flow div{padding:15px 13px;border-right:1px solid var(--line)}.flow div:last-child{border:0}.flow span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.12em}.flow strong{font-size:12px}
    .grid{display:grid;grid-template-columns:1fr 1fr;gap:18px}.card{background:color-mix(in srgb,var(--panel) 94%,transparent);border:1px solid var(--line);border-radius:20px;padding:22px;box-shadow:0 24px 80px #0004}.card.full{grid-column:1/-1}
    .cardhead{display:flex;justify-content:space-between;gap:10px;align-items:center;margin-bottom:18px}.step{font:700 11px/1 ui-monospace,SFMono-Regular,monospace;color:var(--lime);letter-spacing:.08em}.status{font-size:11px;color:var(--muted)}
    .voicebox{display:flex;align-items:center;gap:17px;border:1px solid var(--line);background:#10110f;border-radius:16px;padding:16px}.mic{flex:0 0 64px;width:64px;height:64px;border:0;border-radius:50%;background:var(--lime);color:#0d0f0a;font-size:23px;cursor:pointer;box-shadow:0 0 0 0 #c9ff5840}.mic.recording{background:var(--orange);animation:pulse 1.4s infinite}.mic:disabled{opacity:.45;cursor:not-allowed}@keyframes pulse{70%{box-shadow:0 0 0 14px transparent}}
    .waves{height:34px;display:flex;gap:3px;align-items:center;flex:1}.waves i{display:block;width:3px;height:5px;background:#555750;border-radius:5px}.recording+.voicecopy .waves i{background:var(--orange);animation:wave .7s ease-in-out infinite alternate}.waves i:nth-child(2n){animation-delay:.2s}.waves i:nth-child(3n){animation-delay:.35s}@keyframes wave{to{height:27px}}
    .voicecopy{flex:1}.voicecopy strong,.voicecopy small{display:block}.voicecopy small{color:var(--muted)}.or{display:flex;gap:10px;align-items:center;color:#64655f;margin:15px 0;font-size:11px}.or:before,.or:after{content:"";height:1px;background:var(--line);flex:1}
    textarea,.field input{width:100%;border:1px solid var(--line);background:#10110f;color:var(--ink);border-radius:12px;padding:13px;outline:none}textarea:focus,.field input:focus{border-color:#777b6d}textarea{resize:vertical;min-height:92px}.actions{display:flex;gap:9px;margin-top:12px;flex-wrap:wrap}
    .btn{border:1px solid #44463f;background:#242520;color:var(--ink);border-radius:10px;padding:10px 14px;font-weight:700;cursor:pointer}.btn.primary{background:var(--lime);color:#10120c;border-color:var(--lime)}.btn.danger{background:var(--orange);color:#180b07;border-color:var(--orange)}.btn:disabled{opacity:.4;cursor:not-allowed}
    .provider{display:inline-flex;align-items:center;gap:6px;border-radius:99px;background:#272822;padding:5px 9px;font-size:10px;color:#b8b7b0}.provider:before{content:"";width:6px;height:6px;border-radius:50%;background:#73756d}.provider.live:before{background:var(--lime);box-shadow:0 0 10px var(--lime)}
    .empty{min-height:250px;display:grid;place-items:center;text-align:center;color:#6e7068;padding:35px}.match{display:none}.match.visible{display:block}.product{font-size:23px;line-height:1.15;letter-spacing:-.03em;margin:10px 0}.price{font-size:42px;letter-spacing:-.05em;font-weight:800}.price small{font-size:12px;color:var(--muted);letter-spacing:0}.chips{display:flex;flex-wrap:wrap;gap:6px;margin:14px 0}.chip{font-size:11px;padding:5px 8px;border:1px solid #3a4830;border-radius:99px;color:#cfe7a4}.warning{border-color:#55472f;color:#f0c783}.reason{color:var(--muted);font-size:13px}.qty{font:700 13px ui-monospace,monospace;color:var(--blue)}
    .reviewgrid{display:grid;grid-template-columns:1.2fr 1fr 1fr .65fr;gap:10px}.field label{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.1em;margin:0 0 5px}.check{display:flex;align-items:center;gap:8px;color:var(--muted);font-size:12px;margin:14px 0}.check input{accent-color:var(--lime)}
    .challenge{display:none;margin-top:15px;border-left:3px solid var(--lime);background:#11130e;padding:14px 16px;border-radius:5px}.challenge.visible{display:block}.challenge code{display:block;margin-top:5px;color:#b8d487;overflow-wrap:anywhere}.error{color:#ff9b7d}.fine{color:#777971;font-size:11px;margin-top:12px}.toast{position:fixed;right:22px;bottom:22px;background:#efeee8;color:#151611;border-radius:11px;padding:12px 15px;box-shadow:0 10px 50px #0008;transform:translateY(100px);opacity:0;transition:.25s}.toast.show{transform:none;opacity:1}
    @media(max-width:800px){.hero,.grid{grid-template-columns:1fr}.hero{gap:22px}.flow{grid-template-columns:1fr 1fr}.flow div:nth-child(2){border-right:0}.flow div:nth-child(-n+2){border-bottom:1px solid var(--line)}.card.full{grid-column:auto}.reviewgrid{grid-template-columns:1fr 1fr}.top{margin-bottom:30px}}
  </style>
</head>
<body><main class="shell">
  <div class="top"><div class="brand"><i></i>BuyWith402</div><div class="tag"><b>Voice Workshop</b> · human intent → agent commerce</div></div>
  <section class="hero"><div><div class="eyebrow">Hands busy. Purchase handled.</div><h1>Say what the project needs.</h1><p class="sub">Turn a messy workshop thought into a precise, reviewable hardware order—then hand one x402 payment to an H Company fulfillment agent.</p></div><div class="flow"><div><span>01 · Voice</span><strong>Gradium STT</strong></div><div><span>02 · Resolve</span><strong>Free catalog</strong></div><div><span>03 · Pay</span><strong>x402 / USDC</strong></div><div><span>04 · Fulfill</span><strong>H Company</strong></div></div></section>
  <section class="grid">
    <article class="card"><div class="cardhead"><span class="step">01 / CAPTURE NEED</span><span id="provider" class="provider">No sponsor call yet</span></div>
      <div class="voicebox"><button class="mic" id="mic" aria-label="Start recording">●</button><div class="voicecopy"><strong id="voiceTitle">Tap to speak</strong><small id="voiceHint">Pause, correct yourself, think out loud.</small><div class="waves">${'<i></i>'.repeat(18)}</div></div></div>
      <div class="or">or type a demo request</div><textarea id="transcript" aria-label="Hardware request" placeholder="I need, uh… 200 black 4-40 pan-head Phillips screws, quarter-inch, for the cabinet jig."></textarea>
      <div class="actions"><button class="btn primary" id="resolve">Resolve request</button><button class="btn" id="sample">Load interrupted sample</button></div><div class="fine" id="captureNote">Typed requests are a fallback and are never presented as Gradium transcriptions.</div>
    </article>
    <article class="card"><div class="cardhead"><span class="step">02 / CATALOG MATCH</span><span id="confidence" class="status">Waiting for intent</span></div>
      <div id="empty" class="empty"><div><div style="font-size:32px">⌁</div>Specifications, package math, and all-in price will appear here.</div></div>
      <div id="match" class="match"><div id="sku" class="step"></div><div id="product" class="product"></div><div id="price" class="price"></div><div id="qty" class="qty"></div><div id="chips" class="chips"></div><div id="reason" class="reason"></div></div>
    </article>
    <article class="card full"><div class="cardhead"><span class="step">03 / REVIEW & PREPARE PAYMENT</span><span class="status">Explicit approval required</span></div>
      <div class="reviewgrid"><div class="field"><label>Name</label><input id="name" value="Demo Buyer"></div><div class="field"><label>City</label><input id="city" value="San Francisco"></div><div class="field"><label>State</label><input id="state" maxlength="2" value="CA"></div><div class="field"><label>ZIP</label><input id="zip" value="94107"></div></div>
      <div class="field" style="margin-top:10px"><label>Shipping address</label><input id="address" value="123 Demo Street"></div>
      <label class="check"><input id="dry" type="checkbox" checked> Dry run: H Company agent stops at merchant review and does not place the merchant order</label>
      <label class="check"><input id="approve" type="checkbox"> I reviewed the item, quantity, all-in USDC price, and shipping details</label>
      <div class="actions"><button class="btn danger" id="prepare" disabled>Prepare x402 challenge</button><button class="btn" id="copy" disabled>Copy agent handoff</button></div>
      <div id="challenge" class="challenge"></div><div class="fine">Preparing requests the real paid endpoint without a payment header. It returns a 402 challenge; no money moves until a wallet signs and retries it.</div>
    </article>
  </section>
</main><div id="toast" class="toast"></div>
<script>
const $=id=>document.getElementById(id);let match=null,recording=false,recorder=null,chunks=[],stream=null,source='typed';
const showToast=t=>{const el=$('toast');el.textContent=t;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),1800)};
$('sample').onclick=()=>{$('transcript').value='I need—hang on—one hundred black screws for the cabinet jig. Pan head Phillips, 4-40… quarter-inch long.';source='typed';$('provider').className='provider';$('provider').textContent='Typed demo · no sponsor call';};
$('transcript').addEventListener('input',()=>{source='typed';$('provider').className='provider';$('provider').textContent='Edited text · no new sponsor call';});
function encodeWav(buffer){const channels=buffer.numberOfChannels,length=buffer.length,out=new ArrayBuffer(44+length*2),v=new DataView(out);const put=(o,s)=>[...s].forEach((c,i)=>v.setUint8(o+i,c.charCodeAt(0)));put(0,'RIFF');v.setUint32(4,36+length*2,true);put(8,'WAVE');put(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,buffer.sampleRate,true);v.setUint32(28,buffer.sampleRate*2,true);v.setUint16(32,2,true);v.setUint16(34,16,true);put(36,'data');v.setUint32(40,length*2,true);const data=[...Array(channels)].map((_,i)=>buffer.getChannelData(i));for(let i=0;i<length;i++){let s=0;for(const channel of data)s+=channel[i]/channels;s=Math.max(-1,Math.min(1,s));v.setInt16(44+i*2,s<0?s*32768:s*32767,true)}return new Blob([out],{type:'audio/wav'})}
async function beginRecording(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});const mime=['audio/webm;codecs=opus','audio/ogg;codecs=opus',''].find(x=>!x||MediaRecorder.isTypeSupported(x));recorder=new MediaRecorder(stream,mime?{mimeType:mime}:undefined);chunks=[];recorder.ondataavailable=e=>e.data.size&&chunks.push(e.data);recorder.onstop=transcribeRecording;recorder.start();recording=true;$('mic').classList.add('recording');$('voiceTitle').textContent='Listening… tap to finish';$('voiceHint').textContent='Gradium runs only after you stop.';}catch(e){showToast('Microphone unavailable — use typed fallback')}}
async function transcribeRecording(){recording=false;$('mic').classList.remove('recording');$('mic').disabled=true;$('voiceTitle').textContent='Preparing secure transcription…';try{const blob=new Blob(chunks,{type:recorder.mimeType});const ctx=new AudioContext();const audio=await ctx.decodeAudioData(await blob.arrayBuffer());const wav=encodeWav(audio);await ctx.close();const res=await fetch('/voice/transcribe',{method:'POST',headers:{'content-type':'audio/wav'},body:wav});const data=await res.json();if(!res.ok)throw new Error(data.message||'Transcription unavailable');$('transcript').value=data.transcript;source='gradium';$('provider').className='provider live';$('provider').textContent='Gradium transcription';$('captureNote').textContent='Audio was transcribed by Gradium; the API key remained server-side.';$('voiceTitle').textContent='Transcribed';$('voiceHint').textContent='Review the words, then resolve the request.';}catch(e){source='typed';$('provider').className='provider';$('provider').textContent='No Gradium result';$('captureNote').textContent=e.message+' Type the request below; it will be labeled as typed fallback.';$('voiceTitle').textContent='Voice unavailable';$('voiceHint').textContent='Typed fallback is ready.';}finally{$('mic').disabled=false;stream?.getTracks().forEach(t=>t.stop())}}
$('mic').onclick=()=>{if(recording){recorder.stop();$('voiceTitle').textContent='Finishing…'}else beginRecording()};
$('resolve').onclick=async()=>{const transcript=$('transcript').value.trim();if(!transcript)return showToast('Say or type a hardware need first');$('resolve').disabled=true;try{const res=await fetch('/voice/match',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({transcript})});const data=await res.json();if(!res.ok)throw new Error(data.error||'Could not match');match=data;$('empty').style.display='none';$('match').classList.add('visible');$('sku').textContent=data.product.id;$('product').textContent=data.product.name;$('price').innerHTML=data.product.price_usd+' <small>USDC · all-in</small>';$('qty').textContent=data.quantity+' package'+(data.quantity===1?'':'s')+' × '+data.package_size+' pieces'+(data.requested_units?' · covers '+data.requested_units+' requested':'');$('confidence').textContent=data.confidence.toUpperCase()+' CONFIDENCE';$('chips').innerHTML=data.matched_constraints.map(x=>'<span class="chip">✓ '+x+'</span>').join('')+data.missing_constraints.map(x=>'<span class="chip warning">Review '+x+'</span>').join('');$('reason').textContent=data.rationale;$('approve').checked=false;$('prepare').disabled=true;$('copy').disabled=true;$('challenge').classList.remove('visible');}catch(e){showToast(e.message)}finally{$('resolve').disabled=false}};
$('approve').onchange=()=>{$('prepare').disabled=!$('approve').checked||!match};
function purchaseBody(){return{quantity:match.quantity,dry_run:$('dry').checked,shipping:{name:$('name').value,address_1:$('address').value,city:$('city').value,state:$('state').value.toUpperCase(),zip:$('zip').value,country:'US'}}}
$('prepare').onclick=async()=>{if(!match||!$('approve').checked)return;$('prepare').disabled=true;const path='/products/'+encodeURIComponent(match.product.id)+'/purchase';try{const res=await fetch(path,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(purchaseBody())});const data=await res.json();if(res.status!==402)throw new Error('Expected x402 challenge; received HTTP '+res.status);const amount=data.accepts?.[0]?.amount||data.accepts?.[0]?.maxAmountRequired||'exact amount';const network=data.accepts?.[0]?.network||'Base';const panel=$('challenge');panel.classList.add('visible');panel.replaceChildren();const strong=document.createElement('strong');strong.textContent='402 challenge ready for a wallet agent.';const code=document.createElement('code');code.textContent='POST '+path+' · '+amount+' atomic USDC · '+network;const fine=document.createElement('div');fine.className='fine';fine.textContent='After a signed retry settles, this same endpoint queues the H Company merchant checkout and returns an order ID.';panel.append(strong,code,fine);$('copy').disabled=false;showToast('Challenge prepared — no payment sent');}catch(e){const panel=$('challenge');panel.classList.add('visible');panel.replaceChildren();const error=document.createElement('span');error.className='error';error.textContent=e.message;panel.append(error);}finally{$('prepare').disabled=false}};
$('copy').onclick=async()=>{const path=location.origin+'/products/'+encodeURIComponent(match.product.id)+'/purchase';await navigator.clipboard.writeText('Pay this x402 purchase request and return the order ID.\nPOST '+path+'\nContent-Type: application/json\n\n'+JSON.stringify(purchaseBody(),null,2));showToast('Agent handoff copied')};
</script></body></html>`;
